---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: NAME
  namespace: openshift-gitops
spec:
  destination:
    namespace: NAMESPACE
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/config/apps/NAME
    repoURL: git@github.com:kywa/kywa-learn.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
